-- Calculate total revenue generated by the store.

SELECT SUM(i.Total) AS total_revenue
FROM Invoice i;

-- Calculate revenue by billing country.

SELECT
	i.BillingCountry,
	SUM(i.Total) AS Revenue
FROM Invoice i
GROUP BY i.BillingCountry
ORDER BY Revenue DESC;

-- Display revenue trends by month and year.

SELECT 
    SUBSTR(InvoiceDate, 1, 4) AS Year,
    SUBSTR(InvoiceDate, 6, 2) || '' AS Month,
	SUM(i.Total) AS Revenue
FROM Invoice i
GROUP BY Year, Month
ORDER BY Year, Month;

-- Calculate the average invoice total.

SELECT AVG(i.Total) AS average_total
FROM Invoice i;